name: SSH Tunnel & Forwarding
version: 1.2.0
slug: autossh
description: >-
  'Permanent port forwarding through a simple SSH tunnel'
url: 'https://github.com/ThomDietrich/home-assistant-addons'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
host_network: true
map:
  - 'config:rw'

options:
  hostname: ''
  ssh_port: 22
  username: autossh
  remote_forwarding:
    - '127.0.0.1:8123:172.30.32.1:8123'
  other_ssh_options: '-v -N'
  force_keygen: false
schema:
  hostname: str
  ssh_port: int
  username: str
  remote_forwarding:
    - str
  other_ssh_options: str
  force_keygen: bool
